config/routes.rb
  Rails.application.routes.draw do
  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new', as: "new_user_registration"
    delete 'logout', to: 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  #nested resources allow us to connect comments to products
  resources :products do
    resources :comments
  end
  resources :users
  # , only: [:new, :create, :edit, :update, :destroy]


  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'static_pages#index'
  root 'static_pages#landing_page'
  
  post 'static_pages/thank_you'
#  get 'payments/create'
  post 'payments/create'
#  get 'product/index'
  resources :orders, only: [:index, :show, :create, :destroy]

  # get '/orders', to: 'orders#index'
  # get '/orders', to: 'orders#show'

  #for actiona
  mount ActionCable.server => '/cable'

end
  

app/models/comment.rb
class Comment < ApplicationRecord
	# in rails 5 they are not needed anymore because when we say belongs to user it automatically done this
  #validates :user, presence: :true
  #validates :product, presence: :true

  validates :body, presence: true
  validates :rating, numericality: { only_integer: true }

  after_create_commit { CommentUpdateJob.perform_later(self, self.user) }

  belongs_to :user
  belongs_to :product


  # for desending order means the highest rating at the top
  scope :rating_desc, -> { order(rating: :desc) }

  # for ascending order, lowest at the top...
  scope :rating_asc, -> { order(rating: :asc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    @user = current_user
    respond_to do |format|
      # (byebug)
      if @comment.save
        #ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        #for broadcasting
        #ProductChannel.broadcast_to @product.id, comment: CommentsController.render(partial: 'comments/comment', 
        #  locals: {comment: @comment, current_user: current_user}), average_rating: @product.average_rating
        format.html { redirect_to @product, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

# to delete the comment
  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end




  private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
    <!--for deleting the comment (only admin can do this deletion)-->       
  <% if current_user && current_user.admin? %>
    <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
</div>

app/views/comments/create.js.erb
$("#new_comment").html("Thank you for your review!!");
// $(".product-reviews").prepend("<%= j render @comment %>");
$("#average-rating").attr('data-score', "<%= @product.average_rating %>");