config/routes.rb
  Rails.application.routes.draw do
  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new', as: "new_user_registration"
    delete 'logout', to: 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  #nested resources allow us to connect comments to products
  resources :products do
    resources :comments
  end
  resources :users
  # , only: [:new, :create, :edit, :update, :destroy]


  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'static_pages#index'
  root 'static_pages#landing_page'
  
  post 'static_pages/thank_you'
#  get 'payments/create'
  post 'payments/create'
#  get 'product/index'
  resources :orders, only: [:index, :show, :create, :destroy]

  # get '/orders', to: 'orders#index'
  # get '/orders', to: 'orders#show'

  #for actiona
  mount ActionCable.server => '/cable'

end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
   <!--  <Because CSS is cascading, we want to apply the styles from Bootstrap first, then add any custom styles with our own CSS.> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- We'll link our Bootstrap JavaScript file, as well, after the javascript_include_tag because Bootstrap depends on jQuery, which is loaded with all the other JavaScript
    -->
 		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
 		<!-- For social media button -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
	</head>

  <body>
		<nav class="navbar navbar-default navbar-fixed-top main-navbar">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>	
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand projectname foodie" href="#">@ Foodie</a>
		    </div>
		    <!-- for image -->
		    <!--  <a class="navbar-brand" href="#">
		      <img alt="Brand" src="...">
		    </a> -->
		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">
		        <li>
		        	<%= link_to 'Home',root_path %> <span class="sr-only">(current)</span></a>
		        </li>
		        <!-- <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Offers<span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><a href="#">Sale1</a></li>
		            <li><a href="#">Sale 2</a></li>
		            <li><a href="#">Sale 3</a></li>
		            <li role="separator" class="divider"></li>
		            <li><a href="#">Separated link</a></li>   
		          </ul>
		        </li> -->
				    <li><%= link_to 'Products', products_path %></li>	
		        <li><a href="#">Parties</a></li>
		        <li><%= link_to 'About',static_pages_about_path %></li>
		 				<li><%= link_to 'Contact',static_pages_contact_path %></li>
		        <li><a href="#">FAQ</a></li>
              <!-- In the example, if someone is logged in, they'll see a link to sign out. If no one is logged in, they'll see a link to sign in -->
            <ul class="nav navbar-nav navbar-right pull-right">
             <% if user_signed_in? %>
              <li><%= link_to 'Edit', edit_user_registration_path %></li> 
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
             <% else %>
               <li><%= link_to('Sign Up', new_user_registration_path) %></li>
               <li><%= link_to('Login', new_user_session_path) %></li>
             <% end %>
            </ul>
		      </ul>
          
      <%= form_with(url: products_path, method: 'get', class:"navbar-form navbar-right search-form",local: true) do |form| %>
          <%= form.text_field :q, id: 'q', value: params[:q], placeholder:'Search...', class: "form-control search-box"%>
<!--           <%= form.submit 'Search', class: "btn btn-success btn-padding" %>
 -->          
          <%= button_tag(type: "submit", class: "btn btn-primary search-button") do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>           
        <% end %>
      </div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
		</nav>

    <!-- Add the flash notice tags to somewhere at the top of your application.html.erb template (above or below your navigation, maybe). This block will display a welcome message when you sign in -->
    <% if notice %>
      <div class="alert alert-info alert-message">
        <%= notice %>
      </div>
    <% elsif alert %>
    <div class="alert alert-warning alert-dismissible alert-message" role = "alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="false">&times;</span></button>
      <%= alert %>
    </div>
    <% end %>

    <%= yield %>

    <div class="bodypadding"></div>
  <!--<div class="container"></div> -->
		<!-- Start Footer -->
		<footer id="footer">
			<div class="container text-center">
				<div class="row footerrow">
					<div class="col-lg-12 footer-menu">
						<span class="pull-left">Copyright © 2017 @Foodie. All Rights Reserved. | Made by <a href="http://smartsoftwares.de"> Ammara Irfan</a></span>		
	          <span class="pull-right">
	            <%= link_to 'Home',root_path %>
		        	<%= link_to 'Products', products_path %>
		        	<a href="#">Catering</a>
		        	<a href="#">Parties</a>
			        <%= link_to 'About',static_pages_about_path %>
			 				<%= link_to 'Contact',static_pages_contact_path %>
			        <a href="#">FAQ</a>
	          </span>
					</div>
				</div>
				<!-- 		<a href="https://www.facebook.com/ammara.inayat" class="fa fa-facebook icon"></a>
		 		-->
			</div>
		</footer>
		<!-- End Footer -->
	</body>
</html>